#!/bin/sh
#
# Run testling with a default set of parameters
#
BINDIR=$HOME/bin
export BROWSER=${BROWSER-chrome}
export BVER=${BVER-stable}
BROWSERBIN=$BINDIR/$BROWSER-$BVER
if [ ! -x $BROWSERBIN ]; then
  echo "Installing browser"
  ./node_modules/travis-multirunner/setup.sh
fi
echo "Starting browser"
testling -x start-${BROWSER}